import * as assert from 'assert/strict';
import { SOFTWARE_FACTORY_SAAS_SECURITY_REPORT_CONTRACT_STATUSES, build, validate, render } from '../../software-factory/software-factory-saas-security-report-contract.mjs';
function vS(id, ty, mo, hc) { return { section_id: id, section_type: ty, report_mode: mo, section_hash: hc.repeat(64) }; }
function vI() { return {
  saas_security_report_id: 'ssr-v312', saas_evidence_receipt_id: 'ser-v311', saas_evidence_receipt_ready: true,
  report_sections: [vS('s1','executive_summary','dry-run','a'),vS('s2','saas_scope','dry-run','b'),vS('s3','tenant_isolation','dry-run','c'),vS('s4','subscription_policy','dry-run','d'),vS('s5','billing_controls','dry-run','e'),vS('s6','provider_blockers','dry-run','f'),vS('s7','evidence_receipt','dry-run','0'),vS('s8','pass_gold_status','dry-run','1'),vS('s9','final_blockers','dry-run','2')],
  required_section_types: ['executive_summary','saas_scope','tenant_isolation','subscription_policy','billing_controls','provider_blockers','evidence_receipt','pass_gold_status','final_blockers'],
  report_level: 'contract-only',
};}
const T = [
  () => { assert.ok(Array.isArray(SOFTWARE_FACTORY_SAAS_SECURITY_REPORT_CONTRACT_STATUSES)); console.log('  PASS: STATUSES'); },() => { assert.ok(SOFTWARE_FACTORY_SAAS_SECURITY_REPORT_CONTRACT_STATUSES.includes('SAAS_SECURITY_REPORT_BLOCKED_INPUT')); console.log('  PASS: B_INPUT'); },() => { assert.ok(SOFTWARE_FACTORY_SAAS_SECURITY_REPORT_CONTRACT_STATUSES.includes('SAAS_SECURITY_REPORT_BLOCKED_RECEIPT')); console.log('  PASS: B_RECEIPT'); },() => { assert.ok(SOFTWARE_FACTORY_SAAS_SECURITY_REPORT_CONTRACT_STATUSES.includes('SAAS_SECURITY_REPORT_FAIL')); console.log('  PASS: FAIL'); },() => { assert.ok(SOFTWARE_FACTORY_SAAS_SECURITY_REPORT_CONTRACT_STATUSES.includes('SAAS_SECURITY_REPORT_READY')); console.log('  PASS: READY'); },
  () => { assert.equal(typeof build, 'function'); console.log('  PASS: build'); },() => { assert.equal(typeof validate, 'function'); console.log('  PASS: val'); },() => { assert.equal(typeof render, 'function'); console.log('  PASS: ren'); },
  () => { const r = build(null); assert.ok(r.errors[0].startsWith('SAAS_SECURITY_REPORT_BLOCKED_INPUT')); console.log('  PASS: null'); },() => { const r = build({}); assert.ok(r.errors[0].includes('saas_security_report_id')); console.log('  PASS: {}'); },
  () => { const i = vI(); i.saas_evidence_receipt_ready = false; const r = build(i); assert.ok(r.errors[0].startsWith('SAAS_SECURITY_REPORT_BLOCKED_RECEIPT')); console.log('  PASS: rec not ready'); },() => { const i = vI(); delete i.saas_evidence_receipt_id; const r = build(i); assert.ok(r.errors[0].startsWith('SAAS_SECURITY_REPORT_BLOCKED_RECEIPT')); console.log('  PASS: no ser'); },() => { const i = vI(); i.report_level = 'live'; const r = build(i); assert.ok(r.errors[0].startsWith('SAAS_SECURITY_REPORT_BLOCKED_RECEIPT')); console.log('  PASS: bad level'); },() => { const i = vI(); i.report_sections = []; const r = build(i); assert.ok(r.errors[0].startsWith('SAAS_SECURITY_REPORT_BLOCKED_RECEIPT')); console.log('  PASS: empty'); },
  () => { const i = vI(); i.report_sections = [{ section_type: 'executive_summary', report_mode: 'dry-run', section_hash: 'a'.repeat(64) }]; const r = build(i); assert.ok(r.errors[0].startsWith('SAAS_SECURITY_REPORT_FAIL')); assert.ok(r.errors[0].includes('section_id')); console.log('  PASS: no sid'); },() => { const i = vI(); i.report_sections = [{ section_id: 's1', section_type: 'bad', report_mode: 'dry-run', section_hash: 'a'.repeat(64) }]; const r = build(i); assert.ok(r.errors[0].startsWith('SAAS_SECURITY_REPORT_FAIL')); assert.ok(r.errors[0].includes('section_type')); console.log('  PASS: bad type'); },() => { const i = vI(); i.report_sections = [{ section_id: 's1', section_type: 'executive_summary', report_mode: 'write', section_hash: 'a'.repeat(64) }]; const r = build(i); assert.ok(r.errors[0].startsWith('SAAS_SECURITY_REPORT_FAIL')); assert.ok(r.errors[0].includes('report_mode')); console.log('  PASS: bad mode'); },() => { const i = vI(); i.report_sections = [{ section_id: 's1', section_type: 'executive_summary', report_mode: 'dry-run', section_hash: 'sh' }]; const r = build(i); assert.ok(r.errors[0].startsWith('SAAS_SECURITY_REPORT_FAIL')); assert.ok(r.errors[0].includes('section_hash')); console.log('  PASS: short hash'); },
  () => { const i = vI(); i.required_section_types = ['executive_summary']; const r = build(i); assert.ok(r.errors[0].startsWith('SAAS_SECURITY_REPORT_FAIL')); assert.ok(r.errors[0].includes('missing required section types')); console.log('  PASS: missing req'); },() => { const r = build(vI()); assert.equal(r.saas_security_report_contract_ready, true); assert.equal(r.report_sections_count, 9); assert.equal(r.required_section_types_count, 9); assert.equal(r.errors.length, 0); console.log('  PASS: READY'); },() => { const r = build(vI()); assert.ok(r.saas_security_report_hash); assert.equal(r.saas_security_report_hash.length, 64); console.log('  PASS: hash64'); },() => { const r1 = build(vI()); const r2 = build(vI()); assert.equal(r1.saas_security_report_hash, r2.saas_security_report_hash); console.log('  PASS: det'); },() => { const r = build(vI()); assert.equal(r.saas_report_published, false); assert.equal(r.saas_enabled, false); console.log('  PASS: not published'); },
  () => { const r = build(vI()); const v = validate(r); assert.equal(v.valid, true); console.log('  PASS: vready'); },() => { const r = build(null); const v = validate(r); assert.equal(v.valid, false); console.log('  PASS: vblocked'); },
  () => { const r = render(build(vI())); assert.equal(typeof r, 'string'); assert.ok(r.includes('SAAS_SECURITY_REPORT_READY')); console.log('  PASS: rend'); },() => { const r = render(build(vI())); assert.ok(r.includes('REGRA ABSOLUTA')); console.log('  PASS: REGRA'); },() => { const r = render(null); assert.equal(typeof r, 'string'); console.log('  PASS: null'); },() => { const r = render(build(vI())); assert.ok(r.includes('saas_security_report_hash')); console.log('  PASS: hashren'); },
  () => { const r = build(vI()); ['saas_enabled','tenant_isolation_enforced','subscription_active','billing_executed','billing_provider_connected','invoice_generated','customer_created','webhook_registered','saas_policy_enforced','saas_report_published','saas_authority_granted','saas_phase_passed','enterprise_security_enabled','compliance_enforced','security_scan_executed','secrets_accessed','security_policy_enforced','security_report_published','enterprise_authority_granted','enterprise_phase_passed','dashboard_enabled','dashboard_deployed','multi_project_enabled','policy_enforced','audit_ledger_written','projection_published','release_allowed','deploy_allowed','stable_allowed','tag_allowed','real_execution_allowed','runtime_execution_allowed','runtime_mission_executed','real_pr_creation_allowed','real_patch_execution_allowed','real_patch_applied','production_touched'].forEach(k => assert.equal(r[k], false)); console.log('  PASS: inv'); },() => { const r = build(null); assert.equal(r.saas_report_published, false); assert.equal(r.saas_enabled, false); console.log('  PASS: binv'); },
];
function run() { console.log('\n=== saas-security-report-contract tests ===\n'); const sec = [['exports',0,8],['blocked input',8,10],['blocked receipt',10,14],['fail',14,19],['ready',19,23],['validate',23,25],['render',25,29],['invariants',29,31]]; let p=0,f=0; for (const [l,s,e] of sec) { console.log('--- '+l+' ---'); for (let i=s; i<e; i++) { try { T[i](); p++; } catch (ex) { console.error(`  FAIL: ${ex.message}`); f++; } } } console.log(`\n=== ${p} passed, ${f} failed ===\n`); process.exit(f>0?1:0); } run();