#!/usr/bin/env bash
# setup.sh — Vision Core V2.9.10 Local Setup Script
# Usage: ./setup.sh
# Checks deps, builds go-core, installs backend, creates .env, smoke-tests.
set -euo pipefail

CYAN='\033[0;36m'; GREEN='\033[0;32m'; RED='\033[0;31m'; YELLOW='\033[1;33m'; NC='\033[0m'
BOLD='\033[1m'

info()    { echo -e "${CYAN}[SETUP]${NC} $*"; }
ok()      { echo -e "${GREEN}[OK]${NC} $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }
fail()    { echo -e "${RED}[FAIL]${NC} $*"; exit 1; }

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$REPO_ROOT"

echo -e "${BOLD}"
echo "╔══════════════════════════════════════════════════════════╗"
echo "║         VISION CORE V2.9.10 — LOCAL SETUP               ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# ── 1. Dependency checks ─────────────────────────────────────────
info "Checking dependencies..."

command -v go &>/dev/null || fail "Go not found. Install from https://go.dev/dl/ (require 1.22+)"
GO_VER=$(go version | grep -oP '\d+\.\d+' | head -1)
info "Go $GO_VER found"

command -v node &>/dev/null || fail "Node.js not found. Install from https://nodejs.org (require 20+)"
NODE_VER=$(node --version)
info "Node $NODE_VER found"

command -v npm &>/dev/null || fail "npm not found"
ok "All required dependencies present"

# ── 2. Create directories ────────────────────────────────────────
info "Creating required directories..."
mkdir -p bin backend/data memory
ok "Directories: bin/ backend/data/ memory/"

# ── 3. Build go-core ────────────────────────────────────────────
info "Building go-core binary..."
(
  cd go-core
  go build -o ../bin/vision-core -ldflags="-s -w" ./cmd/vision-core 2>&1
) || fail "go-core build failed"
ok "go-core binary: bin/vision-core"

# ── 4. Generate backend .env ─────────────────────────────────────
if [ -f backend/.env ]; then
  warn "backend/.env already exists — skipping generation"
else
  info "Generating backend/.env..."
  JWT=$(node -e "process.stdout.write(require('crypto').randomBytes(32).toString('hex'))")
  # SESSION_SECRET/PROVIDER_VAULT_SECRET: fail-closed since INCIDENTE-4 and
  # the dogfood cleanup that followed it — backend/server.js refuses to boot
  # without both (see docs/VISION_CORE_BACKEND_SPEC.md). JWT_SECRET above is
  # vestigial (never read by server.js, only referenced in package.json's
  # script metadata) — kept for backward compatibility, not relied upon.
  SESSION=$(node -e "process.stdout.write(require('crypto').randomBytes(32).toString('hex'))")
  VAULT=$(node -e "process.stdout.write(require('crypto').randomBytes(32).toString('hex'))")
  cat > backend/.env << EOF
# Vision Core V2.9.10 — Generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

# Auth
JWT_SECRET=${JWT}
SESSION_SECRET=${SESSION}
PROVIDER_VAULT_SECRET=${VAULT}

# Stripe — placeholders for local dev
STRIPE_SECRET_KEY=sk_test_placeholder
STRIPE_WEBHOOK_SECRET=whsec_placeholder
STRIPE_PRICE_PRO=price_placeholder_pro
STRIPE_PRICE_ENTERPRISE=price_placeholder_enterprise

# GitHub CI
GITHUB_TOKEN=ghp_placeholder
GITHUB_REPO=Imadechumbo/vision-core

# Database
DB_PATH=./data/db.json

# Server
PORT=3000
NODE_ENV=development
EOF
  ok "backend/.env generated with secure SESSION_SECRET + PROVIDER_VAULT_SECRET (backend fails closed without both)"
fi

# ── 5. Install backend npm deps ──────────────────────────────────
info "Installing backend npm dependencies..."
(cd backend && npm install --silent) || fail "npm install failed"
ok "backend/node_modules installed"

# ── 6. Backend syntax + gold validation ─────────────────────────
info "Validating backend syntax..."
(cd backend && node scripts/validate-syntax.js) || fail "Syntax validation failed"
ok "Backend syntax valid"

info "Running self-healing config..."
(cd backend && node scripts/self-healing-config.js --apply > /dev/null 2>&1)
ok "Self-healing config applied"

# ── 7. go-core self-test ─────────────────────────────────────────
info "Running go-core self-test..."
GOCORE_OUT=$(bin/vision-core mission --root "." --input "self-test" 2>/dev/null)
PASS_GOLD=$(echo "$GOCORE_OUT" | node -e "let d=''; process.stdin.on('data',c=>d+=c).on('end',()=>{ try{const j=JSON.parse(d); process.stdout.write(j.pass_gold?'true':'false');} catch{process.stdout.write('parse_error')} })")

if [ "$PASS_GOLD" = "true" ]; then
  ok "go-core self-test: pass_gold=true"
else
  warn "go-core self-test: pass_gold=$PASS_GOLD (non-blocking — check bin/vision-core manually)"
fi

# ── 8. Smoke test backend (optional) ────────────────────────────
info "Smoke-testing backend..."
PORT=3000
node backend/server.js &
BACKEND_PID=$!
sleep 3

if kill -0 $BACKEND_PID 2>/dev/null; then
  HEALTH=$(node -e "
    fetch('http://127.0.0.1:${PORT}/api/health')
      .then(r=>r.json())
      .then(j=>process.stdout.write(j.ok?'ok':'fail'))
      .catch(()=>process.stdout.write('error'))
  " 2>/dev/null || echo "error")

  kill $BACKEND_PID 2>/dev/null || true
  wait $BACKEND_PID 2>/dev/null || true

  if [ "$HEALTH" = "ok" ]; then
    ok "Backend smoke test: /api/health → ok"
  else
    warn "Backend health returned: $HEALTH (check backend logs)"
  fi
else
  warn "Backend process exited early — check backend/.env and logs"
fi

# ── 9. Summary ───────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${GREEN}"
echo "╔══════════════════════════════════════════════════════════╗"
echo "║              VISION CORE SETUP COMPLETE                  ║"
echo "╠══════════════════════════════════════════════════════════╣"
echo "║  go-core binary:  bin/vision-core                        ║"
echo "║  backend .env:    backend/.env                           ║"
echo "║  backend deps:    backend/node_modules/                  ║"
echo "║                                                          ║"
echo "║  To run backend:  cd backend && node server.js           ║"
echo "║  To run tests:    npm run test                           ║"
echo "║  To deploy:       ./deploy.sh --staging                  ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo -e "${NC}"
