import * as assert from 'assert/strict';
import { SOFTWARE_FACTORY_SAAS_FINAL_REVIEW_STATUSES, build, validate, render } from '../../software-factory/software-factory-saas-final-authority-review.mjs';
function vI() { return {
  saas_final_review_id: 'sfr-v313', saas_security_report_id: 'ssr-v312', saas_security_report_contract_ready: true,
  authority_decision: 'approved', authority_id: 'auth-saas-01', review_reason: 'All V305-V313 SaaS hardening modules verified.',
  review_mode: 'contract-only',
  required_review_controls: ['human-authority-required','pass-gold-required','no-real-charge','no-customer-create','no-invoice-create','no-subscription-create','no-webhook-register','no-provider-connect','no-secret-access','no-production-touch','no-deploy','no-release','audit-required','evidence-required'],
};}
const T = [
  () => { assert.ok(Array.isArray(SOFTWARE_FACTORY_SAAS_FINAL_REVIEW_STATUSES)); console.log('  PASS: STATUSES'); },() => { assert.ok(SOFTWARE_FACTORY_SAAS_FINAL_REVIEW_STATUSES.includes('SAAS_FINAL_REVIEW_BLOCKED_INPUT')); console.log('  PASS: B_INPUT'); },() => { assert.ok(SOFTWARE_FACTORY_SAAS_FINAL_REVIEW_STATUSES.includes('SAAS_FINAL_REVIEW_BLOCKED_REPORT')); console.log('  PASS: B_REPORT'); },() => { assert.ok(SOFTWARE_FACTORY_SAAS_FINAL_REVIEW_STATUSES.includes('SAAS_FINAL_REVIEW_DENIED')); console.log('  PASS: DENIED'); },() => { assert.ok(SOFTWARE_FACTORY_SAAS_FINAL_REVIEW_STATUSES.includes('SAAS_FINAL_REVIEW_READY')); console.log('  PASS: READY'); },
  () => { assert.equal(typeof build, 'function'); console.log('  PASS: build'); },() => { assert.equal(typeof validate, 'function'); console.log('  PASS: val'); },() => { assert.equal(typeof render, 'function'); console.log('  PASS: ren'); },
  () => { const r = build(null); assert.ok(r.errors[0].startsWith('SAAS_FINAL_REVIEW_BLOCKED_INPUT')); console.log('  PASS: null'); },() => { const r = build({}); assert.ok(r.errors[0].includes('saas_final_review_id')); console.log('  PASS: {}'); },
  () => { const i = vI(); i.saas_security_report_contract_ready = false; const r = build(i); assert.ok(r.errors[0].startsWith('SAAS_FINAL_REVIEW_BLOCKED_REPORT')); console.log('  PASS: rep not ready'); },() => { const i = vI(); delete i.saas_security_report_id; const r = build(i); assert.ok(r.errors[0].startsWith('SAAS_FINAL_REVIEW_BLOCKED_REPORT')); console.log('  PASS: no ssr'); },() => { const i = vI(); delete i.authority_decision; const r = build(i); assert.ok(r.errors[0].startsWith('SAAS_FINAL_REVIEW_BLOCKED_REPORT')); console.log('  PASS: no decision'); },() => { const i = vI(); delete i.authority_id; const r = build(i); assert.ok(r.errors[0].startsWith('SAAS_FINAL_REVIEW_BLOCKED_REPORT')); console.log('  PASS: no auth id'); },() => { const i = vI(); delete i.review_reason; const r = build(i); assert.ok(r.errors[0].startsWith('SAAS_FINAL_REVIEW_BLOCKED_REPORT')); console.log('  PASS: no reason'); },() => { const i = vI(); i.review_mode = 'live'; const r = build(i); assert.ok(r.errors[0].startsWith('SAAS_FINAL_REVIEW_BLOCKED_REPORT')); console.log('  PASS: bad mode'); },
  () => { const i = vI(); i.authority_decision = 'denied'; const r = build(i); assert.equal(r.errors[0], 'SAAS_FINAL_REVIEW_DENIED: authority_decision is not approved'); console.log('  PASS: denied'); },() => { const i = vI(); i.authority_decision = 'blocked'; const r = build(i); assert.equal(r.errors[0], 'SAAS_FINAL_REVIEW_DENIED: authority_decision is not approved'); console.log('  PASS: blocked'); },() => { const i = vI(); i.required_review_controls = ['human-authority-required']; const r = build(i); assert.ok(r.errors[0].startsWith('SAAS_FINAL_REVIEW_DENIED')); assert.ok(r.errors[0].includes('missing required review controls')); console.log('  PASS: missing controls'); },
  () => { const r = build(vI()); assert.equal(r.saas_final_authority_review_ready, true); assert.equal(r.authority_decision, 'approved'); assert.equal(r.required_review_controls_count, 14); assert.equal(r.errors.length, 0); console.log('  PASS: READY'); },() => { const r = build(vI()); assert.ok(r.final_review_hash); assert.equal(r.final_review_hash.length, 64); console.log('  PASS: hash64'); },() => { const r1 = build(vI()); const r2 = build(vI()); assert.equal(r1.final_review_hash, r2.final_review_hash); console.log('  PASS: det'); },() => { const r = build(vI()); assert.equal(r.saas_authority_granted, false); assert.equal(r.saas_enabled, false); console.log('  PASS: auth not granted'); },
  () => { const r = build(vI()); const v = validate(r); assert.equal(v.valid, true); console.log('  PASS: vready'); },() => { const r = build(null); const v = validate(r); assert.equal(v.valid, false); console.log('  PASS: vblocked'); },
  () => { const r = render(build(vI())); assert.equal(typeof r, 'string'); assert.ok(r.includes('SAAS_FINAL_REVIEW_READY')); console.log('  PASS: rend'); },() => { const r = render(build(vI())); assert.ok(r.includes('REGRA ABSOLUTA')); console.log('  PASS: REGRA'); },() => { const r = render(null); assert.equal(typeof r, 'string'); console.log('  PASS: null'); },() => { const r = render(build(vI())); assert.ok(r.includes('final_review_hash')); console.log('  PASS: hashren'); },
  () => { const r = build(vI()); ['saas_enabled','tenant_isolation_enforced','subscription_active','billing_executed','billing_provider_connected','invoice_generated','customer_created','webhook_registered','saas_policy_enforced','saas_report_published','saas_authority_granted','saas_phase_passed','enterprise_security_enabled','compliance_enforced','security_scan_executed','secrets_accessed','security_policy_enforced','security_report_published','enterprise_authority_granted','enterprise_phase_passed','dashboard_enabled','dashboard_deployed','multi_project_enabled','policy_enforced','audit_ledger_written','projection_published','release_allowed','deploy_allowed','stable_allowed','tag_allowed','real_execution_allowed','runtime_execution_allowed','runtime_mission_executed','real_pr_creation_allowed','real_patch_execution_allowed','real_patch_applied','production_touched'].forEach(k => assert.equal(r[k], false)); console.log('  PASS: inv'); },
  () => { const r = build(null); assert.equal(r.saas_authority_granted, false); assert.equal(r.saas_enabled, false); console.log('  PASS: binv'); },
];
function run() { console.log('\n=== saas-final-authority-review tests ===\n');
  const sec = [['exports',0,8],['blocked input',8,10],['blocked report',10,16],['denied',16,19],['ready',19,23],['validate',23,25],['render',25,29],['invariants',29,31]];
  let p=0,f=0; for (const [l,s,e] of sec) { console.log('--- '+l+' ---'); for (let i=s; i<e; i++) { try { T[i](); p++; } catch (ex) { console.error(`  FAIL: ${ex.message}`); f++; } } }
  console.log(`\n=== ${p} passed, ${f} failed ===\n`); process.exit(f>0?1:0); }
run();