"""
§120 — patch positionBalloon + showStep in vision-core-bundle.js
"""
path = 'frontend/assets/vision-core-bundle.js'
with open(path, 'rb') as f:
    raw = f.read()

# ── verify counts before ──
assert raw.count(b'positionBalloon') >= 2, "positionBalloon not found"
assert raw.count(b'function showStep') == 1, "showStep not found"

# ============================================================
# OLD positionBalloon
# ============================================================
OLD_PB = (
    b"  function positionBalloon(targetEl, pos) {\r\n"
    b"    var balloon = document.getElementById('vcTutorialBalloon');\r\n"
    b"    var pad = 14;\r\n"
    b"    if (!balloon) return;\r\n"
    b"\r\n"
    b"    // Se n\xc3\xa3o tem elemento alvo ou est\xc3\xa1 fora da viewport \xe2\x86\x92 centralizar\r\n"
    b"    var rect = targetEl ? targetEl.getBoundingClientRect() : null;\r\n"
    b"    var vw = window.innerWidth;\r\n"
    b"    var vh = window.innerHeight;\r\n"
    b"    var inView = rect && rect.width > 0 && rect.height > 0\r\n"
    b"                 && rect.top > -rect.height && rect.bottom < vh + rect.height\r\n"
    b"                 && rect.left > -rect.width && rect.right < vw + rect.width;\r\n"
    b"\r\n"
    b"    if (!inView) {\r\n"
    b"      // Centralizar bal\xc3\xa3o na tela\r\n"
    b"      balloon.style.transform = '';\r\n"
    b"      balloon.style.top  = Math.max(80, vh / 2 - 120) + 'px';\r\n"
    b"      balloon.style.left = Math.max(16, vw / 2 - (balloon.offsetWidth || 320) / 2) + 'px';\r\n"
    b"      spotlight.style.cssText = 'top:0;left:0;width:0;height:0;box-shadow:none';\r\n"
    b"      return;\r\n"
    b"    }\r\n"
    b"\r\n"
    b"    // Spotlight\r\n"
    b"    spotlight.style.cssText = '';\r\n"
    b"    spotlight.style.top    = (rect.top - pad) + 'px';\r\n"
    b"    spotlight.style.left   = (rect.left - pad) + 'px';\r\n"
    b"    spotlight.style.width  = (rect.width + pad * 2) + 'px';\r\n"
    b"    spotlight.style.height = (rect.height + pad * 2) + 'px';\r\n"
    b"\r\n"
    b"    var bw = balloon.offsetWidth || 320;\r\n"
    b"    var bh = balloon.offsetHeight || 220;\r\n"
    b"    var top, left;\r\n"
    b"\r\n"
    b"    // Tentar posi\xc3\xa7\xc3\xa3o pedida, fallback para oposta se n\xc3\xa3o couber\r\n"
    b"    if (pos === 'bottom') {\r\n"
    b"      top = rect.bottom + pad + 8;\r\n"
    b"      if (top + bh > vh - 12) top = rect.top - bh - pad - 8; // flip to top\r\n"
    b"    } else {\r\n"
    b"      top = rect.top - bh - pad - 8;\r\n"
    b"      if (top < 12) top = rect.bottom + pad + 8; // flip to bottom\r\n"
    b"    }\r\n"
    b"\r\n"
    b"    left = rect.left + rect.width / 2 - bw / 2;\r\n"
    b"\r\n"
    b"    // Clampar dentro da tela\r\n"
    b"    left = Math.max(16, Math.min(left, vw - bw - 16));\r\n"
    b"    top  = Math.max(70, Math.min(top,  vh - bh - 16));\r\n"
    b"\r\n"
    b"    balloon.style.transform = '';\r\n"
    b"    balloon.style.top  = top + 'px';\r\n"
    b"    balloon.style.left = left + 'px';\r\n"
    b"\r\n"
    b"    // Scroll suave para o elemento\r\n"
    b"    try { targetEl.scrollIntoView({ behavior: 'smooth', block: 'center' }); } catch(e) {}\r\n"
    b"  }"
)

NEW_PB = (
    b"  function positionBalloon(targetEl, pos) {\r\n"
    b"    var balloon = document.getElementById('vcTutorialBalloon');\r\n"
    b"    var pad = 14;\r\n"
    b"    if (!balloon) return;\r\n"
    b"\r\n"
    b"    // Se n\xc3\xa3o tem elemento alvo ou est\xc3\xa1 fora da viewport \xe2\x86\x92 centralizar\r\n"
    b"    var rect = targetEl ? targetEl.getBoundingClientRect() : null;\r\n"
    b"    var vw = window.innerWidth;\r\n"
    b"    var vh = window.innerHeight;\r\n"
    b"    var inView = rect && rect.width > 0 && rect.height > 0\r\n"
    b"                 && rect.top > -rect.height && rect.bottom < vh + rect.height\r\n"
    b"                 && rect.left > -rect.width && rect.right < vw + rect.width;\r\n"
    b"\r\n"
    b"    if (!inView) {\r\n"
    b"      // \xc2\xa7120: passo conceitual \xe2\x80\x94 bal\xc3\xa3o centralizado; overlay escurece uniformemente\r\n"
    b"      // (spotlight a 0x0 mas com box-shadow, sem apagar o efeito visual).\r\n"
    b"      balloon.style.transform = '';\r\n"
    b"      balloon.style.top  = Math.max(80, vh / 2 - 120) + 'px';\r\n"
    b"      balloon.style.left = Math.max(16, vw / 2 - (balloon.offsetWidth || 320) / 2) + 'px';\r\n"
    b"      spotlight.style.cssText = 'top:0;left:0;width:0;height:0;box-shadow:0 0 0 9999px rgba(0,0,0,0.55)';\r\n"
    b"      return;\r\n"
    b"    }\r\n"
    b"\r\n"
    b"    // Spotlight sobre o elemento real\r\n"
    b"    spotlight.style.cssText = '';\r\n"
    b"    spotlight.style.top    = (rect.top - pad) + 'px';\r\n"
    b"    spotlight.style.left   = (rect.left - pad) + 'px';\r\n"
    b"    spotlight.style.width  = (rect.width + pad * 2) + 'px';\r\n"
    b"    spotlight.style.height = (rect.height + pad * 2) + 'px';\r\n"
    b"\r\n"
    b"    var bw = balloon.offsetWidth || 320;\r\n"
    b"    var bh = balloon.offsetHeight || 220;\r\n"
    b"\r\n"
    b"    // \xc2\xa7120: \xc3\xa1rea do spotlight expandida com pad \xe2\x80\x94 o bal\xc3\xa3o nunca deve cair dentro dela.\r\n"
    b"    var spT = rect.top  - pad;\r\n"
    b"    var spL = rect.left - pad;\r\n"
    b"    var spR = rect.right  + pad;\r\n"
    b"    var spB = rect.bottom + pad;\r\n"
    b"\r\n"
    b"    // Dois ret\xc3\xa2ngulos se sobrep\xc3\xb5em quando N\xc3\x83O \xc3\xa9 verdade que um est\xc3\xa1 fora do outro.\r\n"
    b"    function overlaps(t, l) {\r\n"
    b"      return !(l + bw <= spL || l >= spR || t + bh <= spT || t >= spB);\r\n"
    b"    }\r\n"
    b"\r\n"
    b"    // \xc2\xa7120: quando o alvo \xc3\xa9 mais largo que o bal\xc3\xa3o * 1.5, ancora na borda esquerda\r\n"
    b"    // em vez de centralizar \xe2\x80\x94 evita que o bal\xc3\xa3o centralizado caia dentro do spotlight.\r\n"
    b"    var isWide = rect.width > bw * 1.5;\r\n"
    b"    function calcPos(candidate) {\r\n"
    b"      var t, l;\r\n"
    b"      if (candidate === 'bottom') {\r\n"
    b"        t = rect.bottom + pad + 8;\r\n"
    b"        l = isWide ? rect.left + 8 : rect.left + rect.width / 2 - bw / 2;\r\n"
    b"      } else if (candidate === 'top') {\r\n"
    b"        t = rect.top - bh - pad - 8;\r\n"
    b"        l = isWide ? rect.left + 8 : rect.left + rect.width / 2 - bw / 2;\r\n"
    b"      } else if (candidate === 'right') {\r\n"
    b"        t = rect.top + rect.height / 2 - bh / 2;\r\n"
    b"        l = rect.right + pad + 8;\r\n"
    b"      } else { // left\r\n"
    b"        t = rect.top + rect.height / 2 - bh / 2;\r\n"
    b"        l = rect.left - bw - pad - 8;\r\n"
    b"      }\r\n"
    b"      l = Math.max(16, Math.min(l, vw - bw - 16));\r\n"
    b"      t = Math.max(70, Math.min(t, vh - bh - 16));\r\n"
    b"      return { t: t, l: l };\r\n"
    b"    }\r\n"
    b"\r\n"
    b"    // Ordem de tentativa: posi\xc3\xa7\xc3\xa3o pedida, oposta, lados.\r\n"
    b"    var order = pos === 'bottom'\r\n"
    b"      ? ['bottom', 'top', 'right', 'left']\r\n"
    b"      : ['top', 'bottom', 'right', 'left'];\r\n"
    b"\r\n"
    b"    var chosen = null;\r\n"
    b"    for (var ci = 0; ci < order.length; ci++) {\r\n"
    b"      var p = calcPos(order[ci]);\r\n"
    b"      if (!overlaps(p.t, p.l)) { chosen = p; break; }\r\n"
    b"    }\r\n"
    b"\r\n"
    b"    // Fallback: elemento ocupa quase toda a viewport \xe2\x80\x94 usa posi\xc3\xa7\xc3\xa3o pedida sem garantia.\r\n"
    b"    if (!chosen) { chosen = calcPos(pos); }\r\n"
    b"\r\n"
    b"    balloon.style.transform = '';\r\n"
    b"    balloon.style.top  = chosen.t + 'px';\r\n"
    b"    balloon.style.left = chosen.l + 'px';\r\n"
    b"\r\n"
    b"    // Scroll suave para o elemento\r\n"
    b"    try { targetEl.scrollIntoView({ behavior: 'smooth', block: 'center' }); } catch(e) {}\r\n"
    b"  }"
)

# ============================================================
# OLD showStep
# ============================================================
OLD_SS = (
    b"  function showStep(idx) {\r\n"
    b"    var step = STEPS[idx];\r\n"
    b"    titleEl.textContent   = step.title;\r\n"
    b"    counterEl.textContent = (idx + 1) + ' / ' + STEPS.length;\r\n"
    b"    prevBtn.style.display = idx === 0 ? 'none' : '';\r\n"
    b"    nextBtn.textContent   = idx === STEPS.length - 1 ? 'Fechar' : 'Pr\xc3\xb3ximo \xe2\x86\x92';\r\n"
    b"    if (ctaBtn) { step.cta ? ctaBtn.classList.remove('hidden') : ctaBtn.classList.add('hidden'); }\r\n"
    b"    typeText(step.text, textEl, null);\r\n"
    b"    // \xc2\xa7118: onEnter \xe2\x80\x94 aciona navega\xc3\xa7\xc3\xa3o/reveal antes de medir getBoundingClientRect\r\n"
    b"    if (typeof step.onEnter === 'function') { try { step.onEnter(); } catch(e) {} }\r\n"
    b"    // getEl dentro do setTimeout para CSS/transi\xc3\xa7\xc3\xa3o assentar (mesmo padr\xc3\xa3o original)\r\n"
    b"    setTimeout(function() { positionBalloon(getEl(step.target), step.pos); }, 80);\r\n"
    b"  }"
)

NEW_SS = (
    b"  function showStep(idx) {\r\n"
    b"    var step = STEPS[idx];\r\n"
    b"    titleEl.textContent   = step.title;\r\n"
    b"    counterEl.textContent = (idx + 1) + ' / ' + STEPS.length;\r\n"
    b"    prevBtn.style.display = idx === 0 ? 'none' : '';\r\n"
    b"    nextBtn.textContent   = idx === STEPS.length - 1 ? 'Fechar' : 'Pr\xc3\xb3ximo \xe2\x86\x92';\r\n"
    b"    if (ctaBtn) { step.cta ? ctaBtn.classList.remove('hidden') : ctaBtn.classList.add('hidden'); }\r\n"
    b"    typeText(step.text, textEl, null);\r\n"
    b"    // \xc2\xa7118: onEnter \xe2\x80\x94 aciona navega\xc3\xa7\xc3\xa3o/reveal antes de medir getBoundingClientRect\r\n"
    b"    if (typeof step.onEnter === 'function') { try { step.onEnter(); } catch(e) {} }\r\n"
    b"    // \xc2\xa7120: passos com onEnter usam 200ms (renderiza\xc3\xa7\xc3\xa3o precisa assentar);\r\n"
    b"    // se o elemento ainda n\xc3\xa3o estiver em view na 1\xc2\xaa tentativa, retenta 1x com 150ms extra.\r\n"
    b"    var _delay = step.onEnter ? 200 : 80;\r\n"
    b"    setTimeout(function() {\r\n"
    b"      var el = getEl(step.target);\r\n"
    b"      var r  = el ? el.getBoundingClientRect() : null;\r\n"
    b"      var _vw = window.innerWidth, _vh = window.innerHeight;\r\n"
    b"      var inV = r && r.width > 0 && r.height > 0\r\n"
    b"                && r.top > -r.height && r.bottom < _vh + r.height\r\n"
    b"                && r.left > -r.width  && r.right  < _vw + r.width;\r\n"
    b"      if (!inV && el) {\r\n"
    b"        // Elemento existe mas ainda n\xc3\xa3o assentou \xe2\x80\x94 retenta uma vez\r\n"
    b"        setTimeout(function() { positionBalloon(getEl(step.target), step.pos); }, 150);\r\n"
    b"      } else {\r\n"
    b"        positionBalloon(el, step.pos);\r\n"
    b"      }\r\n"
    b"    }, _delay);\r\n"
    b"  }"
)

# Apply
result = raw

assert OLD_PB in result, "OLD_PB not in file"
result = result.replace(OLD_PB, NEW_PB, 1)
print("positionBalloon: replaced OK")

assert OLD_SS in result, "OLD_SS not in file"
result = result.replace(OLD_SS, NEW_SS, 1)
print("showStep: replaced OK")

with open(path, 'wb') as f:
    f.write(result)

print("Written:", len(result), "bytes")
print("DONE")
