'use strict';

/**
 * VISION CORE v1.7 — Obsidian Vault
 *
 * Cria notas Markdown sanitizadas no vault Obsidian (sistema de arquivos real).
 * Obsidian = biblioteca humana/comunitária. Hermes Memory = memória operacional.
 *
 * REGRA CRÍTICA: notas Obsidian NÃO entram automaticamente na Hermes Memory.
 * Só após reproduced + PASS GOLD confirmado a nota pode ser promovida.
 */

const fs   = require('fs');
const path = require('path');

const CFG_PATH = path.resolve(__dirname, '../../config/obsidian.json');

// ── Carregar configuração ─────────────────────────────────────────────────
function loadConfig() {
  try {
    return JSON.parse(fs.readFileSync(CFG_PATH, 'utf-8'));
  } catch {
    return {
      enabled:   true,
      vaultPath: path.resolve(__dirname, '../../data/obsidian-vault'),
      folders: {
        inbox:      '00_INBOX_COMMUNITY',
        triaged:    '01_TRIAGED',
        benchmarks: '02_BENCHMARKS',
        solved:     '03_SOLVED_PASS_GOLD',
        rejected:   '04_REJECTED_SENSITIVE',
        templates:  '90_TEMPLATES',
      },
    };
  }
}

// ── Resolver path de uma pasta do vault ──────────────────────────────────
function folderPath(folderKey) {
  const cfg  = loadConfig();
  const base = cfg.vaultPath;
  const name = cfg.folders[folderKey] || folderKey;
  const full = path.resolve(base, name);
  fs.mkdirSync(full, { recursive: true });
  return full;
}

// ── Slug para nome de arquivo ─────────────────────────────────────────────
function slugify(text) {
  return String(text || 'untitled')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60);
}

// ── Nota Markdown ─────────────────────────────────────────────────────────
function buildMarkdown(feedback) {
  const {
    id, title, status, category, framework, language, environment, severity,
    errorSignature, stackTraceSanitized, reproductionSteps, attemptedSolution,
    openclawClassification, benchmarkCandidate, passGoldResult, promotedToHermes,
    submittedAt,
  } = feedback;

  const ocl = openclawClassification || {};

  return [
    `# ${title || 'Community Feedback'}`,
    '',
    '> ⚠️ **This note does NOT automatically enter Hermes validated memory.**',
    '> Promotion requires manual triage + reproduction + PASS GOLD.',
    '',
    '## Metadata',
    `- **ID:** ${id || 'N/A'}`,
    `- **Status:** ${status || 'submitted'}`,
    `- **Submitted:** ${submittedAt || new Date().toISOString()}`,
    `- **Category:** ${category || 'unknown'}`,
    `- **Framework:** ${framework || 'unknown'}`,
    `- **Language:** ${language || 'unknown'}`,
    `- **Environment:** ${environment || 'unknown'}`,
    `- **Severity:** ${severity || 'medium'}`,
    '',
    '## Error Signature',
    '```',
    (errorSignature || '(none)').slice(0, 300),
    '```',
    '',
    '## Stack Trace (Sanitized)',
    '```txt',
    (stackTraceSanitized || '[no stack trace]').slice(0, 800),
    '```',
    '',
    '## OpenClaw Classification',
    `- **Category detected:** ${ocl.category || 'unknown'}`,
    `- **Agents:** ${Array.isArray(ocl.agents) ? ocl.agents.join(', ') : 'none'}`,
    `- **Priority:** ${ocl.priority || 'N/A'}`,
    `- **Escalation level:** ${ocl.escalationLevel || 'N/A'}`,
    '',
    '## Reproduction Steps',
    (reproductionSteps || '(not provided)').slice(0, 600),
    '',
    '## Attempted Solution',
    (attemptedSolution || '(not provided)').slice(0, 600),
    '',
    '## Benchmark',
    `- **Benchmark candidate:** ${benchmarkCandidate ? '✅ yes' : '❌ no'}`,
    `- **PASS GOLD result:** ${passGoldResult || 'pending'}`,
    `- **Promoted to Hermes:** ${promotedToHermes ? '✅ yes' : '❌ no'}`,
    '',
    '---',
    '_Generated by VISION CORE Community Feedback Harness._',
    '_Secrets and private paths are automatically redacted._',
  ].join('\n');
}

// ── Criar nota no vault ───────────────────────────────────────────────────
function createMarkdownNote(feedback, folderKey = 'inbox') {
  const cfg = loadConfig();
  if (!cfg.enabled) return { ok: false, reason: 'Vault desabilitado' };

  try {
    const dir      = folderPath(folderKey);
    const slug     = slugify(feedback.title || feedback.id || 'feedback');
    const ts       = Date.now();
    const fileName = `${slug}-${ts}.md`;
    const filePath = path.join(dir, fileName);

    fs.writeFileSync(filePath, buildMarkdown(feedback), 'utf-8');
    console.log(`[VAULT] ✔ Nota criada: ${folderKey}/${fileName}`);
    return { ok: true, fileName, folder: folderKey, filePath };
  } catch (e) {
    console.warn('[VAULT] Erro ao criar nota:', e.message);
    return { ok: false, error: e.message };
  }
}

// ── Mover nota entre pastas ───────────────────────────────────────────────
function moveNote(fileName, fromFolderKey, toFolderKey, newStatus) {
  const cfg = loadConfig();
  if (!cfg.enabled) return { ok: false, reason: 'Vault desabilitado' };

  try {
    const srcDir  = folderPath(fromFolderKey);
    const dstDir  = folderPath(toFolderKey);
    const srcPath = path.join(srcDir, fileName);
    const dstPath = path.join(dstDir, fileName);

    if (!fs.existsSync(srcPath)) {
      // Tentar localizar o arquivo em qualquer pasta do vault
      const found = findNoteAnywhere(fileName, cfg);
      if (!found) return { ok: false, error: `Arquivo não encontrado: ${fileName}` };
      let content = fs.readFileSync(found, 'utf-8');
      if (newStatus) content = content.replace(/- \*\*Status:\*\* \S+/, `- **Status:** ${newStatus}`);
      fs.writeFileSync(dstPath, content, 'utf-8');
      fs.unlinkSync(found);
    } else {
      let content = fs.readFileSync(srcPath, 'utf-8');
      if (newStatus) content = content.replace(/- \*\*Status:\*\* \S+/, `- **Status:** ${newStatus}`);
      fs.writeFileSync(dstPath, content, 'utf-8');
      fs.unlinkSync(srcPath);
    }

    console.log(`[VAULT] ✔ Nota movida: ${fromFolderKey} → ${toFolderKey}`);
    return { ok: true, fileName, from: fromFolderKey, to: toFolderKey };
  } catch (e) {
    console.warn('[VAULT] Erro ao mover nota:', e.message);
    return { ok: false, error: e.message };
  }
}

// ── Salvar stub de rejeição ───────────────────────────────────────────────
function saveRejectedStub(payload, reason) {
  const cfg = loadConfig();
  if (!cfg.enabled) return { ok: false };

  try {
    const dir      = folderPath('rejected');
    const ts       = Date.now();
    const fileName = `rejected-${ts}.md`;
    const content  = [
      '# Rejected Submission',
      '',
      `> ⛔ Rejected: ${reason}`,
      '',
      `- **Rejected at:** ${new Date().toISOString()}`,
      `- **Reason:** ${reason}`,
      `- **Category hint:** ${payload?.category || 'unknown'}`,
      '',
      '_Content was NOT stored. Submission rejected due to sensitive content._',
    ].join('\n');

    fs.writeFileSync(path.join(dir, fileName), content, 'utf-8');
    console.log(`[VAULT] ⛔ Stub rejeitado criado: ${fileName}`);
    return { ok: true, fileName, folder: 'rejected' };
  } catch (e) {
    return { ok: false, error: e.message };
  }
}

// ── Criar templates padrão ────────────────────────────────────────────────
function ensureTemplates() {
  const cfg = loadConfig();
  if (!cfg.enabled) return;
  try {
    const dir      = folderPath('templates');
    const tmplPath = path.join(dir, 'feedback-template.md');
    if (fs.existsSync(tmplPath)) return;
    fs.writeFileSync(tmplPath, [
      '# {{error_title}}',
      '',
      '## Status',
      'submitted',
      '',
      '## Category',
      'upload_multer | server_port | cors | auth_token | database | generic',
      '',
      '## Framework',
      'Node.js / Express',
      '',
      '## Severity',
      'low | medium | high | critical',
      '',
      '## Error Signature',
      '```',
      'paste sanitized error message here',
      '```',
      '',
      '## Stack Trace Sanitized',
      '```txt',
      '[redact secrets and paths before submitting]',
      '```',
    ].join('\n'), 'utf-8');
  } catch { /* templates são opcionais */ }
}

// ── Listar arquivos de uma pasta ──────────────────────────────────────────
function listFolder(folderKey) {
  try {
    return fs.readdirSync(folderPath(folderKey)).filter(f => f.endsWith('.md'));
  } catch { return []; }
}

// ── Encontrar nota em qualquer pasta ─────────────────────────────────────
function findNoteAnywhere(fileName, cfg) {
  for (const key of Object.keys(cfg.folders)) {
    try {
      const p = path.join(cfg.vaultPath, cfg.folders[key], fileName);
      if (fs.existsSync(p)) return p;
    } catch { /* continuar */ }
  }
  return null;
}

ensureTemplates();

module.exports = { createMarkdownNote, moveNote, saveRejectedStub, listFolder, buildMarkdown, loadConfig };
