$ErrorActionPreference = "Stop"

Write-Host "=== ROLLBACK PLAN V6.0 - DOCUMENTAL ==="
Write-Host "tag estavel: v5.9-main-gold"
Write-Host ""
Write-Host "1) Pre-condicao:"
Write-Host "   - rollback so permitido se validacao pos-deploy falhar."
Write-Host ""
Write-Host "2) Comandos Git de referencia:"
Write-Host "   git fetch --tags origin"
Write-Host "   git checkout main"
Write-Host "   git reset --hard v5.9-main-gold"
Write-Host "   git status"
Write-Host ""
Write-Host "3) Backend:"
Write-Host "   - Rebuild backend na revisao v5.9-main-gold"
Write-Host "   - Reiniciar servico backend"
Write-Host "   - Validar /api/health e /api/go-core/health"
Write-Host ""
Write-Host "4) Frontend:"
Write-Host "   - Publicar frontend da revisao v5.9-main-gold"
Write-Host "   - Invalidar cache CDN se aplicavel"
Write-Host "   - Validar HTTP 200 no dominio frontend"
Write-Host ""
Write-Host "5) Pos-rollback:"
Write-Host "   - Executar scripts/post-deploy-validate-v60.ps1"
Write-Host "   - Confirmar PASS GOLD apos estabilizacao"
