package github

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func goldGates() GateSnapshot {
	return GateSnapshot{PassGold: true, PassSecure: true, DeployAllowed: true, PromotionAllowed: true, SecurityBlockingTotal: 0, RollbackReady: true, ValidatorOK: true, PatcherOK: true}
}

func TestBuildPRPlanCanOpenWithGoldGates(t *testing.T) {
	plan := BuildPRPlan(PRPlanInput{MissionID: "mission_123", ChangedFiles: []string{"a.go"}, IssueType: "cors", GateSnapshot: goldGates()})
	if !plan.CanOpenPR {
		t.Fatalf("expected can open, blocked: %s", plan.BlockReason)
	}
	if plan.BaseBranch != DefaultBaseBranch {
		t.Fatalf("default base branch mismatch: %s", plan.BaseBranch)
	}
	if plan.WorkBranch != "vision/remediation/mission_123" {
		t.Fatalf("work branch mismatch: %s", plan.WorkBranch)
	}
}

func TestBuildPRPlanBlocksFailedGates(t *testing.T) {
	tests := []struct {
		name   string
		mutate func(*GateSnapshot)
		want   string
	}{
		{"pass gold", func(g *GateSnapshot) { g.PassGold = false }, "pass_gold"},
		{"pass secure", func(g *GateSnapshot) { g.PassSecure = false }, "pass_secure"},
		{"blocking", func(g *GateSnapshot) { g.SecurityBlockingTotal = 1 }, "security_blocking_total"},
		{"rollback", func(g *GateSnapshot) { g.RollbackReady = false }, "rollback_ready"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			g := goldGates()
			tt.mutate(&g)
			plan := BuildPRPlan(PRPlanInput{MissionID: "m", ChangedFiles: []string{"a.go"}, IssueType: "x", GateSnapshot: g})
			if plan.CanOpenPR || !strings.Contains(plan.BlockReason, tt.want) {
				t.Fatalf("expected block containing %q, got can=%v reason=%q", tt.want, plan.CanOpenPR, plan.BlockReason)
			}
		})
	}
}

func TestBuildPRPlanBlocksEmptyChangedFiles(t *testing.T) {
	plan := BuildPRPlan(PRPlanInput{MissionID: "m", IssueType: "x", GateSnapshot: goldGates()})
	if plan.CanOpenPR || !strings.Contains(plan.BlockReason, "changed_files") {
		t.Fatalf("expected empty changed_files block, got %#v", plan)
	}
}

func TestBuildPRPlanSanitizesBranchAndBody(t *testing.T) {
	plan := BuildPRPlan(PRPlanInput{MissionID: " mission/../bad ~^:?*[\\ id ", ChangedFiles: []string{"a.go"}, IssueType: "cors", SuggestedStrategy: "patch", PatchSummary: "updated CORS", GateSnapshot: goldGates()})
	if !IsSafeBranchName(plan.WorkBranch) {
		t.Fatalf("unsafe branch: %q", plan.WorkBranch)
	}
	for _, want := range []string{"Mission ID:", "PASS GOLD: true", "PASS SECURE: true", "a.go", "Generated by Vision Aegis Core"} {
		if !strings.Contains(plan.Body, want) {
			t.Fatalf("body missing %q:\n%s", want, plan.Body)
		}
	}
}

func TestGitRejectsUnsafeBranchName(t *testing.T) {
	dir := initRepo(t)
	if err := CreateBranch(dir, "bad branch"); err == nil {
		t.Fatal("expected unsafe branch rejection")
	}
}

func TestAddFilesRejectsDeniedAndTraversal(t *testing.T) {
	dir := initRepo(t)
	for _, f := range []string{".vision-memory/a.jsonl", ".vision-snapshots/a", "../escape"} {
		if err := AddFiles(dir, []string{f}); err == nil {
			t.Fatalf("expected AddFiles to reject %s", f)
		}
	}
}

func TestCommitNotCreatedIfNoFiles(t *testing.T) {
	dir := initRepo(t)
	if _, err := Commit(dir, "test"); err == nil {
		t.Fatal("expected no staged files error")
	}
}

func TestEnsureCleanWorkingTree(t *testing.T) {
	dir := initRepo(t)
	if err := EnsureCleanWorkingTree(dir); err != nil {
		t.Fatalf("expected clean tree: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "changed.txt"), []byte("x"), 0644); err != nil {
		t.Fatal(err)
	}
	if err := EnsureCleanWorkingTree(dir); err == nil {
		t.Fatal("expected dirty tree")
	}
	if err := EnsureWorkingTreeOnlyHas(dir, []string{"changed.txt"}); err != nil {
		t.Fatalf("expected planned dirty tree accepted: %v", err)
	}
}

func TestMockPRClientDeterministicURLAndDryRun(t *testing.T) {
	mock := &MockPRClient{}
	resp, err := mock.OpenPR(context.Background(), OpenPRRequest{Owner: "acme", Repo: "vision"})
	if err != nil || resp.URL != "https://github.com/acme/vision/pull/1" {
		t.Fatalf("unexpected mock response: %#v %v", resp, err)
	}
	plan := BuildPRPlan(PRPlanInput{MissionID: "m", ChangedFiles: []string{"a.go"}, IssueType: "x", GateSnapshot: goldGates()})
	res := OpenPRDryRunAware(context.Background(), OpenFlowInput{DryRun: true, Plan: plan, Client: mock})
	if !res.OK || res.PROpened || mock.OpenCalls != 1 {
		t.Fatalf("dry-run should not call client/open PR: res=%#v calls=%d", res, mock.OpenCalls)
	}
}

func TestHTTPClientRefusesWithoutTokenAndDoesNotLeakToken(t *testing.T) {
	t.Setenv("VISION_GITHUB_WRITE", "1")
	t.Setenv("GITHUB_TOKEN", "")
	_, err := (HTTPGitHubClient{}).OpenPR(context.Background(), OpenPRRequest{})
	if err == nil {
		t.Fatal("expected missing token error")
	}
	if strings.Contains(err.Error(), "GITHUB_TOKEN") || strings.Contains(err.Error(), "secret") {
		t.Fatalf("error leaks token detail: %s", err.Error())
	}
}

func TestBuildPassGoldStatus(t *testing.T) {
	if s := BuildPassGoldStatus(goldGates()); s.State != "success" || s.Context != DefaultStatusContext {
		t.Fatalf("expected success status, got %#v", s)
	}
	g := goldGates()
	g.PassGold = false
	if s := BuildPassGoldStatus(g); s.State != "failure" {
		t.Fatalf("expected failure for passgold")
	}
	g = goldGates()
	g.PassSecure = false
	if s := BuildPassGoldStatus(g); s.State != "failure" {
		t.Fatalf("expected failure for passsecure")
	}
	g = goldGates()
	g.SecurityBlockingTotal = 1
	if s := BuildPassGoldStatus(g); s.State != "failure" {
		t.Fatalf("expected failure for blocking")
	}
}

func initRepo(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	runGit(t, dir, "init")
	runGit(t, dir, "config", "user.email", "vision@example.invalid")
	runGit(t, dir, "config", "user.name", "Vision Test")
	if err := os.WriteFile(filepath.Join(dir, "README.md"), []byte("init\n"), 0644); err != nil {
		t.Fatal(err)
	}
	runGit(t, dir, "add", "README.md")
	runGit(t, dir, "commit", "-m", "init")
	return dir
}

func runGit(t *testing.T, dir string, args ...string) {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("git %v failed: %v\n%s", args, err, out)
	}
}
