package github

import (
	"fmt"
	"regexp"
	"strings"
)

const (
	DefaultBaseBranch    = "v6-go-enterprise-runtime"
	DefaultStatusContext = "vision/pass-gold"
)

type PRPlan struct {
	ID                 string   `json:"id"`
	MissionID          string   `json:"mission_id"`
	BaseBranch         string   `json:"base_branch"`
	WorkBranch         string   `json:"work_branch"`
	CommitMessage      string   `json:"commit_message"`
	Title              string   `json:"title"`
	Body               string   `json:"body"`
	ChangedFiles       []string `json:"changed_files"`
	PassGoldRequired   bool     `json:"pass_gold_required"`
	PassSecureRequired bool     `json:"pass_secure_required"`
	CanOpenPR          bool     `json:"can_open_pr"`
	BlockReason        string   `json:"block_reason,omitempty"`
	StatusContext      string   `json:"status_context"`
	StatusState        string   `json:"status_state"`
}

type PRResult struct {
	OK              bool   `json:"ok"`
	PlanID          string `json:"plan_id"`
	BranchCreated   bool   `json:"branch_created"`
	CommitCreated   bool   `json:"commit_created"`
	CommitSHA       string `json:"commit_sha,omitempty"`
	PROpened        bool   `json:"pr_opened"`
	PRNumber        int    `json:"pr_number,omitempty"`
	PRURL           string `json:"pr_url,omitempty"`
	StatusPublished bool   `json:"status_published"`
	Error           string `json:"error,omitempty"`
}

type GateSnapshot struct {
	PassGold              bool `json:"pass_gold"`
	PassSecure            bool `json:"pass_secure"`
	DeployAllowed         bool `json:"deploy_allowed"`
	PromotionAllowed      bool `json:"promotion_allowed"`
	SecurityBlockingTotal int  `json:"security_blocking_total"`
	RollbackReady         bool `json:"rollback_ready"`
	ValidatorOK           bool `json:"validator_ok"`
	PatcherOK             bool `json:"patcher_ok"`
}

type PRPlanInput struct {
	MissionID         string
	BaseBranch        string
	WorkBranchPrefix  string
	ChangedFiles      []string
	IssueType         string
	SuggestedStrategy string
	PatchSummary      string
	GateSnapshot      GateSnapshot
}

func BuildPRPlan(input PRPlanInput) PRPlan {
	missionID := sanitizeSegment(defaultString(input.MissionID, "mission"))
	base := defaultString(input.BaseBranch, DefaultBaseBranch)
	prefix := defaultString(input.WorkBranchPrefix, "vision/remediation")
	workBranch := sanitizeBranch(prefix + "/" + missionID)
	issueType := defaultString(strings.TrimSpace(input.IssueType), "unspecified issue")
	changedFiles := dedupeNonEmpty(input.ChangedFiles)
	plan := PRPlan{
		ID:                 "prplan_" + missionID,
		MissionID:          input.MissionID,
		BaseBranch:         base,
		WorkBranch:         workBranch,
		CommitMessage:      fmt.Sprintf("fix(vision): apply supervised remediation for %s", issueType),
		Title:              fmt.Sprintf("VISION remediation: %s", issueType),
		ChangedFiles:       changedFiles,
		PassGoldRequired:   true,
		PassSecureRequired: true,
		StatusContext:      DefaultStatusContext,
		StatusState:        BuildPassGoldStatus(input.GateSnapshot).State,
	}
	plan.Body = buildPRBody(input, plan, issueType)
	plan.BlockReason = firstBlockReason(input.GateSnapshot, changedFiles)
	plan.CanOpenPR = plan.BlockReason == ""
	return plan
}

func buildPRBody(input PRPlanInput, plan PRPlan, issueType string) string {
	g := input.GateSnapshot
	files := "- none"
	if len(plan.ChangedFiles) > 0 {
		lines := make([]string, 0, len(plan.ChangedFiles))
		for _, f := range plan.ChangedFiles {
			lines = append(lines, "- "+f)
		}
		files = strings.Join(lines, "\n")
	}
	return fmt.Sprintf(`# VISION remediation: %s

Generated by Vision Aegis Core.

## Mission
- Mission ID: %s
- Suggested strategy: %s
- Patch summary: %s

## PASS gates
- PASS GOLD: %t
- PASS SECURE: %t
- Security blocking total: %d
- Deploy allowed: %t
- Promotion allowed: %t

## Rollback and validation
- Rollback ready: %t
- Validator OK: %t
- Patcher OK: %t

## Changed files
%s
`, issueType, input.MissionID, defaultString(input.SuggestedStrategy, "not provided"), defaultString(input.PatchSummary, "not provided"), g.PassGold, g.PassSecure, g.SecurityBlockingTotal, g.DeployAllowed, g.PromotionAllowed, g.RollbackReady, g.ValidatorOK, g.PatcherOK, files)
}

func firstBlockReason(g GateSnapshot, changedFiles []string) string {
	switch {
	case !g.PassGold:
		return "pass_gold is false"
	case !g.PassSecure:
		return "pass_secure is false"
	case !g.DeployAllowed:
		return "deploy_allowed is false"
	case !g.PromotionAllowed:
		return "promotion_allowed is false"
	case g.SecurityBlockingTotal != 0:
		return "security_blocking_total is greater than zero"
	case !g.RollbackReady:
		return "rollback_ready is false"
	case !g.ValidatorOK:
		return "validator_ok is false"
	case !g.PatcherOK:
		return "patcher_ok is false"
	case len(changedFiles) == 0:
		return "changed_files is empty"
	default:
		return ""
	}
}

func IsSafeBranchName(branch string) bool {
	return branch != "" && branch != "main" && branch != "master" && branch == sanitizeBranch(branch) && !strings.HasPrefix(branch, "/") && !strings.HasSuffix(branch, "/") && !strings.Contains(branch, "//") && !strings.Contains(branch, "..")
}

func sanitizeBranch(branch string) string {
	branch = strings.TrimSpace(branch)
	branch = strings.ReplaceAll(branch, "\\", "/")
	invalid := regexp.MustCompile(`[\s~^:?*\[]+`)
	branch = invalid.ReplaceAllString(branch, "-")
	for strings.Contains(branch, "..") {
		branch = strings.ReplaceAll(branch, "..", ".")
	}
	for strings.Contains(branch, "//") {
		branch = strings.ReplaceAll(branch, "//", "/")
	}
	branch = strings.Trim(branch, "/.")
	if branch == "" {
		return "vision/remediation/mission"
	}
	return branch
}

func sanitizeSegment(segment string) string {
	segment = strings.ReplaceAll(segment, "/", "-")
	return sanitizeBranch(segment)
}

func dedupeNonEmpty(values []string) []string {
	seen := map[string]bool{}
	out := []string{}
	for _, v := range values {
		v = strings.TrimSpace(v)
		if v == "" || seen[v] {
			continue
		}
		seen[v] = true
		out = append(out, v)
	}
	return out
}

func defaultString(value, fallback string) string {
	if strings.TrimSpace(value) == "" {
		return fallback
	}
	return strings.TrimSpace(value)
}
